import 'models.dart';

const achievements = <AchievementDef>[
  AchievementDef(
    id: 'first_spot',
    title: 'Первый спот',
    description: 'Заспоттить первую машину',
    emoji: '📸',
  ),
  AchievementDef(
    id: 'german_trio',
    title: 'Немецкая тройка',
    description: 'Собрать BMW, Audi и Mercedes',
    emoji: '🇩🇪',
  ),
  AchievementDef(
    id: 'king_of_tuning',
    title: 'Король тюнинга',
    description: '5 машин с обвесом',
    emoji: '🛠️',
  ),
  AchievementDef(
    id: 'night_spotter',
    title: 'Ночной споттер',
    description: 'Спот с 00:00 до 05:00',
    emoji: '🌙',
  ),
  AchievementDef(
    id: 'legendary_catch',
    title: 'Легенда в кадре',
    description: 'Поймать Legendary-машину',
    emoji: '👑',
  ),
  AchievementDef(
    id: 'ten_spots',
    title: 'Десять кадров',
    description: '10 машин в гараже',
    emoji: '🔟',
  ),
  AchievementDef(
    id: 'japan_pack',
    title: 'JDM-охотник',
    description: 'Toyota, Nissan и Honda в гараже',
    emoji: '🇯🇵',
  ),
  AchievementDef(
    id: 'millionaire',
    title: 'Гараж на миллион',
    description: 'Суммарная стоимость от 1 000 000 ₽',
    emoji: '💰',
  ),
  AchievementDef(
    id: 'italian_job',
    title: 'Итальянский акцент',
    description: 'Ferrari, Lamborghini или Pagani',
    emoji: '🇮🇹',
  ),
  AchievementDef(
    id: 'city_walker',
    title: 'Городской',
    description: 'Указать свой город',
    emoji: '📍',
  ),
];

const carCatalog = <CarSpec>[
  CarSpec(
    id: 'lada_vesta',
    make: 'Lada',
    model: 'Vesta',
    generation: 'NG',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 122,
    zeroToHundred: 10.5,
    drivetrain: 'FWD',
    priceRub: 1650000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'kia_rio',
    make: 'Kia',
    model: 'Rio',
    generation: 'IV',
    yearFrom: 2017,
    yearTo: 2023,
    bodyType: 'седан',
    horsepower: 123,
    zeroToHundred: 10.3,
    drivetrain: 'FWD',
    priceRub: 1400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'hyundai_solaris',
    make: 'Hyundai',
    model: 'Solaris',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 123,
    zeroToHundred: 10.2,
    drivetrain: 'FWD',
    priceRub: 1450000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'vw_polo',
    make: 'Volkswagen',
    model: 'Polo',
    generation: 'Liftback',
    yearFrom: 2020,
    yearTo: 2024,
    bodyType: 'лифтбек',
    horsepower: 110,
    zeroToHundred: 10.4,
    drivetrain: 'FWD',
    priceRub: 1600000,
    rarity: Rarity.common,
    aliases: ['vw polo'],
  ),
  CarSpec(
    id: 'skoda_octavia',
    make: 'Skoda',
    model: 'Octavia',
    generation: 'A8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'лифтбек',
    horsepower: 150,
    zeroToHundred: 8.5,
    drivetrain: 'FWD',
    priceRub: 2400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'hyundai_creta',
    make: 'Hyundai',
    model: 'Creta',
    generation: 'II',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 150,
    zeroToHundred: 10.1,
    drivetrain: 'FWD',
    priceRub: 2500000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'kia_sportage',
    make: 'Kia',
    model: 'Sportage',
    generation: 'V',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 180,
    zeroToHundred: 9.1,
    drivetrain: 'AWD',
    priceRub: 3200000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'toyota_camry',
    make: 'Toyota',
    model: 'Camry',
    generation: 'XV70',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 249,
    zeroToHundred: 7.2,
    drivetrain: 'FWD',
    priceRub: 3100000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'toyota_rav4',
    make: 'Toyota',
    model: 'RAV4',
    generation: 'XA50',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 199,
    zeroToHundred: 8.5,
    drivetrain: 'AWD',
    priceRub: 3600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'mazda_cx5',
    make: 'Mazda',
    model: 'CX-5',
    generation: 'KF',
    yearFrom: 2017,
    yearTo: 2025,
    bodyType: 'кроссовер',
    horsepower: 194,
    zeroToHundred: 8.9,
    drivetrain: 'AWD',
    priceRub: 3300000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'renault_logan',
    make: 'Renault',
    model: 'Logan',
    generation: 'II',
    yearFrom: 2014,
    yearTo: 2022,
    bodyType: 'седан',
    horsepower: 113,
    zeroToHundred: 10.7,
    drivetrain: 'FWD',
    priceRub: 900000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'bmw_3',
    make: 'BMW',
    model: '3 Series',
    generation: 'G20',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 258,
    zeroToHundred: 5.8,
    drivetrain: 'RWD',
    priceRub: 5200000,
    rarity: Rarity.rare,
    aliases: ['bmw 3', 'bmw 320', 'bmw 330'],
  ),
  CarSpec(
    id: 'bmw_5',
    make: 'BMW',
    model: '5 Series',
    generation: 'G60',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 286,
    zeroToHundred: 5.8,
    drivetrain: 'AWD',
    priceRub: 7800000,
    rarity: Rarity.rare,
    aliases: ['bmw 5', 'bmw 530'],
  ),
  CarSpec(
    id: 'mercedes_c',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    generation: 'W206',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 258,
    zeroToHundred: 6.0,
    drivetrain: 'RWD',
    priceRub: 6100000,
    rarity: Rarity.rare,
    aliases: ['mercedes c', 'c-class', 'c200', 'c300'],
  ),
  CarSpec(
    id: 'mercedes_e',
    make: 'Mercedes-Benz',
    model: 'E-Class',
    generation: 'W214',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 258,
    zeroToHundred: 6.1,
    drivetrain: 'AWD',
    priceRub: 8900000,
    rarity: Rarity.rare,
    aliases: ['mercedes e', 'e-class'],
  ),
  CarSpec(
    id: 'audi_a4',
    make: 'Audi',
    model: 'A4',
    generation: 'B9',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 249,
    zeroToHundred: 5.8,
    drivetrain: 'AWD',
    priceRub: 4800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_a6',
    make: 'Audi',
    model: 'A6',
    generation: 'C8',
    yearFrom: 2018,
    yearTo: 2025,
    bodyType: 'седан',
    horsepower: 340,
    zeroToHundred: 5.1,
    drivetrain: 'AWD',
    priceRub: 7200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'lexus_rx',
    make: 'Lexus',
    model: 'RX',
    generation: 'AL30',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 279,
    zeroToHundred: 7.0,
    drivetrain: 'AWD',
    priceRub: 8500000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_x5',
    make: 'BMW',
    model: 'X5',
    generation: 'G05',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 5.5,
    drivetrain: 'AWD',
    priceRub: 9800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'porsche_macan',
    make: 'Porsche',
    model: 'Macan',
    generation: 'I',
    yearFrom: 2019,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 265,
    zeroToHundred: 6.2,
    drivetrain: 'AWD',
    priceRub: 7900000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'subaru_wrx',
    make: 'Subaru',
    model: 'WRX',
    generation: 'VB',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 275,
    zeroToHundred: 5.4,
    drivetrain: 'AWD',
    priceRub: 5200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'mazda_mx5',
    make: 'Mazda',
    model: 'MX-5',
    generation: 'ND',
    yearFrom: 2015,
    yearTo: 2026,
    bodyType: 'родстер',
    horsepower: 184,
    zeroToHundred: 6.5,
    drivetrain: 'RWD',
    priceRub: 4100000,
    rarity: Rarity.rare,
    aliases: ['miata'],
  ),
  CarSpec(
    id: 'toyota_prado',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    generation: '150',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'внедорожник',
    horsepower: 249,
    zeroToHundred: 9.7,
    drivetrain: 'AWD',
    priceRub: 6200000,
    rarity: Rarity.rare,
    aliases: ['prado'],
  ),
  CarSpec(
    id: 'bmw_m3',
    make: 'BMW',
    model: 'M3',
    generation: 'G80',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 510,
    zeroToHundred: 3.9,
    drivetrain: 'AWD',
    priceRub: 14500000,
    rarity: Rarity.epic,
    aliases: ['m3 competition'],
  ),
  CarSpec(
    id: 'bmw_m5',
    make: 'BMW',
    model: 'M5',
    generation: 'F90',
    yearFrom: 2018,
    yearTo: 2023,
    bodyType: 'седан',
    horsepower: 625,
    zeroToHundred: 3.3,
    drivetrain: 'AWD',
    priceRub: 12800000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'amg_c63',
    make: 'Mercedes-AMG',
    model: 'C63',
    generation: 'W206',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 680,
    zeroToHundred: 3.4,
    drivetrain: 'AWD',
    priceRub: 16800000,
    rarity: Rarity.epic,
    aliases: ['c63', 'c 63'],
  ),
  CarSpec(
    id: 'audi_rs6',
    make: 'Audi',
    model: 'RS6 Avant',
    generation: 'C8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'универсал',
    horsepower: 630,
    zeroToHundred: 3.4,
    drivetrain: 'AWD',
    priceRub: 17500000,
    rarity: Rarity.epic,
    aliases: ['rs6', 'rs 6'],
  ),
  CarSpec(
    id: 'porsche_911',
    make: 'Porsche',
    model: '911 Carrera',
    generation: '992',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 394,
    zeroToHundred: 4.0,
    drivetrain: 'RWD',
    priceRub: 18500000,
    rarity: Rarity.epic,
    aliases: ['911', 'carrera'],
  ),
  CarSpec(
    id: 'nissan_gtr',
    make: 'Nissan',
    model: 'GT-R',
    generation: 'R35',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 570,
    zeroToHundred: 2.9,
    drivetrain: 'AWD',
    priceRub: 14000000,
    rarity: Rarity.epic,
    aliases: ['gtr', 'godzilla'],
  ),
  CarSpec(
    id: 'toyota_supra',
    make: 'Toyota',
    model: 'Supra',
    generation: 'A90',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 387,
    zeroToHundred: 4.1,
    drivetrain: 'RWD',
    priceRub: 9200000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'mustang_gt',
    make: 'Ford',
    model: 'Mustang GT',
    generation: 'S650',
    yearFrom: 2024,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 486,
    zeroToHundred: 4.3,
    drivetrain: 'RWD',
    priceRub: 8900000,
    rarity: Rarity.epic,
    aliases: ['mustang'],
  ),
  CarSpec(
    id: 'corvette_c8',
    make: 'Chevrolet',
    model: 'Corvette',
    generation: 'C8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 495,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'g_class',
    make: 'Mercedes-Benz',
    model: 'G-Class',
    generation: 'W463',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 585,
    zeroToHundred: 4.5,
    drivetrain: 'AWD',
    priceRub: 22000000,
    rarity: Rarity.epic,
    aliases: ['гелик', 'g-wagen', 'g63', 'g 63'],
  ),
  CarSpec(
    id: 'audi_r8',
    make: 'Audi',
    model: 'R8',
    generation: '4S',
    yearFrom: 2019,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 620,
    zeroToHundred: 3.1,
    drivetrain: 'AWD',
    priceRub: 21000000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'honda_nsx',
    make: 'Honda',
    model: 'NSX',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 581,
    zeroToHundred: 3.0,
    drivetrain: 'AWD',
    priceRub: 16000000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'nissan_silvia',
    make: 'Nissan',
    model: 'Silvia',
    generation: 'S15',
    yearFrom: 1999,
    yearTo: 2002,
    bodyType: 'купе',
    horsepower: 250,
    zeroToHundred: 5.5,
    drivetrain: 'RWD',
    priceRub: 4500000,
    rarity: Rarity.epic,
    aliases: ['s15', '200sx'],
  ),
  CarSpec(
    id: 'toyota_mark2',
    make: 'Toyota',
    model: 'Mark II',
    generation: 'JZX90',
    yearFrom: 1992,
    yearTo: 1996,
    bodyType: 'седан',
    horsepower: 280,
    zeroToHundred: 6.3,
    drivetrain: 'RWD',
    priceRub: 1800000,
    rarity: Rarity.rare,
    aliases: ['марк', 'jzx'],
  ),
  CarSpec(
    id: 'porsche_gt3rs',
    make: 'Porsche',
    model: '911 GT3 RS',
    generation: '992',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 525,
    zeroToHundred: 3.2,
    drivetrain: 'RWD',
    priceRub: 42000000,
    rarity: Rarity.legendary,
    aliases: ['gt3 rs', 'gt3rs'],
  ),
  CarSpec(
    id: 'ferrari_f8',
    make: 'Ferrari',
    model: 'F8 Tributo',
    generation: 'F8',
    yearFrom: 2019,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 720,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    priceRub: 38000000,
    rarity: Rarity.legendary,
    aliases: ['f8'],
  ),
  CarSpec(
    id: 'lambo_huracan',
    make: 'Lamborghini',
    model: 'Huracán',
    generation: 'LP610',
    yearFrom: 2014,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 640,
    zeroToHundred: 2.9,
    drivetrain: 'AWD',
    priceRub: 36000000,
    rarity: Rarity.legendary,
    aliases: ['huracan', 'huracán'],
  ),
  CarSpec(
    id: 'lambo_aventador',
    make: 'Lamborghini',
    model: 'Aventador',
    generation: 'SVJ',
    yearFrom: 2018,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 770,
    zeroToHundred: 2.8,
    drivetrain: 'AWD',
    priceRub: 55000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'mclaren_720s',
    make: 'McLaren',
    model: '720S',
    generation: 'P14',
    yearFrom: 2017,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 720,
    zeroToHundred: 2.8,
    drivetrain: 'RWD',
    priceRub: 40000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'bugatti_chiron',
    make: 'Bugatti',
    model: 'Chiron',
    generation: 'I',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 1500,
    zeroToHundred: 2.4,
    drivetrain: 'AWD',
    priceRub: 280000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'ferrari_sf90',
    make: 'Ferrari',
    model: 'SF90 Stradale',
    generation: 'SF90',
    yearFrom: 2019,
    yearTo: 2025,
    bodyType: 'купе',
    horsepower: 1000,
    zeroToHundred: 2.5,
    drivetrain: 'AWD',
    priceRub: 62000000,
    rarity: Rarity.legendary,
    aliases: ['sf90'],
  ),
  CarSpec(
    id: 'rolls_phantom',
    make: 'Rolls-Royce',
    model: 'Phantom',
    generation: 'VIII',
    yearFrom: 2017,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 571,
    zeroToHundred: 5.3,
    drivetrain: 'RWD',
    priceRub: 70000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'koenigsegg_jesko',
    make: 'Koenigsegg',
    model: 'Jesko',
    generation: 'I',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 1600,
    zeroToHundred: 2.5,
    drivetrain: 'RWD',
    priceRub: 320000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'pagani_huayra',
    make: 'Pagani',
    model: 'Huayra',
    generation: 'I',
    yearFrom: 2012,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 730,
    zeroToHundred: 3.0,
    drivetrain: 'RWD',
    priceRub: 180000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'honda_civic',
    make: 'Honda',
    model: 'Civic',
    generation: 'XI',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 180,
    zeroToHundred: 7.5,
    drivetrain: 'FWD',
    priceRub: 2800000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'nissan_qashqai',
    make: 'Nissan',
    model: 'Qashqai',
    generation: 'J12',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 158,
    zeroToHundred: 9.2,
    drivetrain: 'FWD',
    priceRub: 2700000,
    rarity: Rarity.common,
  ),
];

CarSpec? matchCatalog(String make, String model) {
  final needle = _norm('$make $model');
  if (needle.trim().isEmpty) return null;

  CarSpec? best;
  var bestScore = 0;
  for (final car in carCatalog) {
    final names = [
      '${car.make} ${car.model}',
      car.model,
      ...car.aliases,
    ].map(_norm);
    for (final name in names) {
      var score = 0;
      if (needle == name) {
        score = 100;
      } else if (needle.contains(name) || name.contains(needle)) {
        score = 70 + name.length;
      } else {
        final parts = needle.split(' ');
        final hits = parts.where((p) => p.length > 1 && name.contains(p)).length;
        score = hits * 20;
      }
      if (score > bestScore) {
        bestScore = score;
        best = car;
      }
    }
  }
  return bestScore >= 40 ? best : null;
}

String _norm(String value) {
  return value
      .toLowerCase()
      .replaceAll('mercedes-benz', 'mercedes')
      .replaceAll('mercedes benz', 'mercedes')
      .replaceAll('volkswagen', 'vw')
      .replaceAll(RegExp(r'[^a-z0-9а-яё ]'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
}
