import 'models.dart';

const carCatalog = <CarSpec>[
  CarSpec(
    id: 'lada_vesta',
    make: 'Lada',
    model: 'Vesta',
    generation: 'NG',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 122,
    zeroToHundred: 10.5,
    drivetrain: 'FWD',
    priceRub: 1650000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'lada_granta',
    make: 'Lada',
    model: 'Granta',
    generation: 'II',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 90,
    zeroToHundred: 11.6,
    drivetrain: 'FWD',
    priceRub: 980000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'lada_niva',
    make: 'Lada',
    model: 'Niva Travel',
    generation: 'I',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 80,
    zeroToHundred: 13.5,
    drivetrain: 'AWD',
    priceRub: 1450000,
    rarity: Rarity.common,
    aliases: ['niva', 'нива'],
  ),
  CarSpec(
    id: 'uaz_patriot',
    make: 'UAZ',
    model: 'Patriot',
    generation: 'I',
    yearFrom: 2015,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 150,
    zeroToHundred: 13.2,
    drivetrain: 'AWD',
    priceRub: 1800000,
    rarity: Rarity.common,
    aliases: ['уаз'],
  ),
  CarSpec(
    id: 'kia_rio',
    make: 'Kia',
    model: 'Rio',
    generation: 'IV',
    yearFrom: 2017,
    yearTo: 2023,
    bodyType: 'седан',
    horsepower: 123,
    zeroToHundred: 10.3,
    drivetrain: 'FWD',
    priceRub: 1400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'kia_k5',
    make: 'Kia',
    model: 'K5',
    generation: 'III',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 194,
    zeroToHundred: 8.6,
    drivetrain: 'FWD',
    priceRub: 2900000,
    rarity: Rarity.common,
    aliases: ['optima'],
  ),
  CarSpec(
    id: 'kia_cerato',
    make: 'Kia',
    model: 'Cerato',
    generation: 'IV',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 150,
    zeroToHundred: 9.8,
    drivetrain: 'FWD',
    priceRub: 2200000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'kia_sportage',
    make: 'Kia',
    model: 'Sportage',
    generation: 'V',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 180,
    zeroToHundred: 9.1,
    drivetrain: 'AWD',
    priceRub: 3200000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'kia_sorento',
    make: 'Kia',
    model: 'Sorento',
    generation: 'IV',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 249,
    zeroToHundred: 7.8,
    drivetrain: 'AWD',
    priceRub: 4200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'hyundai_solaris',
    make: 'Hyundai',
    model: 'Solaris',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 123,
    zeroToHundred: 10.2,
    drivetrain: 'FWD',
    priceRub: 1450000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'hyundai_elantra',
    make: 'Hyundai',
    model: 'Elantra',
    generation: 'VII',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 150,
    zeroToHundred: 9.4,
    drivetrain: 'FWD',
    priceRub: 2500000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'hyundai_creta',
    make: 'Hyundai',
    model: 'Creta',
    generation: 'II',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 150,
    zeroToHundred: 10.1,
    drivetrain: 'FWD',
    priceRub: 2500000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'hyundai_tucson',
    make: 'Hyundai',
    model: 'Tucson',
    generation: 'IV',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 180,
    zeroToHundred: 8.8,
    drivetrain: 'AWD',
    priceRub: 3400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'hyundai_santafe',
    make: 'Hyundai',
    model: 'Santa Fe',
    generation: 'V',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 249,
    zeroToHundred: 8.0,
    drivetrain: 'AWD',
    priceRub: 4500000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'vw_polo',
    make: 'Volkswagen',
    model: 'Polo',
    generation: 'Liftback',
    yearFrom: 2020,
    yearTo: 2024,
    bodyType: 'лифтбек',
    horsepower: 110,
    zeroToHundred: 10.4,
    drivetrain: 'FWD',
    priceRub: 1600000,
    rarity: Rarity.common,
    aliases: ['vw polo'],
  ),
  CarSpec(
    id: 'vw_golf',
    make: 'Volkswagen',
    model: 'Golf',
    generation: 'VIII',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'хэтчбек',
    horsepower: 150,
    zeroToHundred: 8.5,
    drivetrain: 'FWD',
    priceRub: 2800000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'vw_passat',
    make: 'Volkswagen',
    model: 'Passat',
    generation: 'B8',
    yearFrom: 2015,
    yearTo: 2023,
    bodyType: 'седан',
    horsepower: 190,
    zeroToHundred: 7.7,
    drivetrain: 'FWD',
    priceRub: 2600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'vw_tiguan',
    make: 'Volkswagen',
    model: 'Tiguan',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 180,
    zeroToHundred: 7.7,
    drivetrain: 'AWD',
    priceRub: 3400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'vw_touareg',
    make: 'Volkswagen',
    model: 'Touareg',
    generation: 'III',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 5.9,
    drivetrain: 'AWD',
    priceRub: 7200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'skoda_octavia',
    make: 'Skoda',
    model: 'Octavia',
    generation: 'A8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'лифтбек',
    horsepower: 150,
    zeroToHundred: 8.5,
    drivetrain: 'FWD',
    priceRub: 2400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'skoda_rapid',
    make: 'Skoda',
    model: 'Rapid',
    generation: 'II',
    yearFrom: 2020,
    yearTo: 2024,
    bodyType: 'лифтбек',
    horsepower: 110,
    zeroToHundred: 10.2,
    drivetrain: 'FWD',
    priceRub: 1700000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'skoda_kodiaq',
    make: 'Skoda',
    model: 'Kodiaq',
    generation: 'I',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 180,
    zeroToHundred: 8.0,
    drivetrain: 'AWD',
    priceRub: 3600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'skoda_superb',
    make: 'Skoda',
    model: 'Superb',
    generation: 'III',
    yearFrom: 2015,
    yearTo: 2023,
    bodyType: 'лифтбек',
    horsepower: 220,
    zeroToHundred: 7.0,
    drivetrain: 'AWD',
    priceRub: 3100000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'toyota_camry',
    make: 'Toyota',
    model: 'Camry',
    generation: 'XV70',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 249,
    zeroToHundred: 7.2,
    drivetrain: 'FWD',
    priceRub: 3100000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'toyota_corolla',
    make: 'Toyota',
    model: 'Corolla',
    generation: 'E210',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 140,
    zeroToHundred: 9.3,
    drivetrain: 'FWD',
    priceRub: 2400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'toyota_rav4',
    make: 'Toyota',
    model: 'RAV4',
    generation: 'XA50',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 199,
    zeroToHundred: 8.5,
    drivetrain: 'AWD',
    priceRub: 3600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'toyota_lc300',
    make: 'Toyota',
    model: 'Land Cruiser 300',
    generation: 'J300',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 415,
    zeroToHundred: 6.8,
    drivetrain: 'AWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
    aliases: ['крузак', 'land cruiser'],
  ),
  CarSpec(
    id: 'toyota_prado',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    generation: '150',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'внедорожник',
    horsepower: 249,
    zeroToHundred: 9.7,
    drivetrain: 'AWD',
    priceRub: 6200000,
    rarity: Rarity.rare,
    aliases: ['prado'],
  ),
  CarSpec(
    id: 'toyota_hilux',
    make: 'Toyota',
    model: 'Hilux',
    generation: 'VIII',
    yearFrom: 2015,
    yearTo: 2026,
    bodyType: 'пикап',
    horsepower: 204,
    zeroToHundred: 10.7,
    drivetrain: 'AWD',
    priceRub: 4800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'toyota_supra',
    make: 'Toyota',
    model: 'Supra',
    generation: 'A90',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 387,
    zeroToHundred: 4.1,
    drivetrain: 'RWD',
    priceRub: 9200000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'toyota_mark2',
    make: 'Toyota',
    model: 'Mark II',
    generation: 'JZX90',
    yearFrom: 1992,
    yearTo: 1996,
    bodyType: 'седан',
    horsepower: 280,
    zeroToHundred: 6.3,
    drivetrain: 'RWD',
    priceRub: 1800000,
    rarity: Rarity.rare,
    aliases: ['марк', 'jzx'],
  ),
  CarSpec(
    id: 'toyota_ae86',
    make: 'Toyota',
    model: 'Sprinter Trueno',
    generation: 'AE86',
    yearFrom: 1983,
    yearTo: 1987,
    bodyType: 'купе',
    horsepower: 130,
    zeroToHundred: 8.3,
    drivetrain: 'RWD',
    priceRub: 2500000,
    rarity: Rarity.epic,
    aliases: ['ae86', 'хачироку'],
  ),
  CarSpec(
    id: 'mazda_cx5',
    make: 'Mazda',
    model: 'CX-5',
    generation: 'KF',
    yearFrom: 2017,
    yearTo: 2025,
    bodyType: 'кроссовер',
    horsepower: 194,
    zeroToHundred: 8.9,
    drivetrain: 'AWD',
    priceRub: 3300000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'mazda_3',
    make: 'Mazda',
    model: '3',
    generation: 'BP',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 186,
    zeroToHundred: 8.2,
    drivetrain: 'FWD',
    priceRub: 2600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'mazda_6',
    make: 'Mazda',
    model: '6',
    generation: 'GJ',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 231,
    zeroToHundred: 7.8,
    drivetrain: 'FWD',
    priceRub: 2800000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'mazda_mx5',
    make: 'Mazda',
    model: 'MX-5',
    generation: 'ND',
    yearFrom: 2015,
    yearTo: 2026,
    bodyType: 'родстер',
    horsepower: 184,
    zeroToHundred: 6.5,
    drivetrain: 'RWD',
    priceRub: 4100000,
    rarity: Rarity.rare,
    aliases: ['miata'],
  ),
  CarSpec(
    id: 'renault_logan',
    make: 'Renault',
    model: 'Logan',
    generation: 'II',
    yearFrom: 2014,
    yearTo: 2022,
    bodyType: 'седан',
    horsepower: 113,
    zeroToHundred: 10.7,
    drivetrain: 'FWD',
    priceRub: 900000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'renault_duster',
    make: 'Renault',
    model: 'Duster',
    generation: 'II',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 150,
    zeroToHundred: 10.3,
    drivetrain: 'AWD',
    priceRub: 2100000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'renault_arkana',
    make: 'Renault',
    model: 'Arkana',
    generation: 'I',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 150,
    zeroToHundred: 10.2,
    drivetrain: 'AWD',
    priceRub: 2300000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'honda_civic',
    make: 'Honda',
    model: 'Civic',
    generation: 'XI',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 180,
    zeroToHundred: 7.5,
    drivetrain: 'FWD',
    priceRub: 2800000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'honda_accord',
    make: 'Honda',
    model: 'Accord',
    generation: 'XI',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 192,
    zeroToHundred: 7.2,
    drivetrain: 'FWD',
    priceRub: 3600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'honda_crv',
    make: 'Honda',
    model: 'CR-V',
    generation: 'VI',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 190,
    zeroToHundred: 8.5,
    drivetrain: 'AWD',
    priceRub: 4200000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'honda_nsx',
    make: 'Honda',
    model: 'NSX',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 581,
    zeroToHundred: 3.0,
    drivetrain: 'AWD',
    priceRub: 16000000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'honda_s2000',
    make: 'Honda',
    model: 'S2000',
    generation: 'AP2',
    yearFrom: 2003,
    yearTo: 2009,
    bodyType: 'родстер',
    horsepower: 240,
    zeroToHundred: 6.2,
    drivetrain: 'RWD',
    priceRub: 3500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'honda_civic_r',
    make: 'Honda',
    model: 'Civic Type R',
    generation: 'FL5',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'хэтчбек',
    horsepower: 330,
    zeroToHundred: 5.4,
    drivetrain: 'FWD',
    priceRub: 7200000,
    rarity: Rarity.epic,
    aliases: ['type r'],
  ),
  CarSpec(
    id: 'nissan_qashqai',
    make: 'Nissan',
    model: 'Qashqai',
    generation: 'J12',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 158,
    zeroToHundred: 9.2,
    drivetrain: 'FWD',
    priceRub: 2700000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'nissan_xtrail',
    make: 'Nissan',
    model: 'X-Trail',
    generation: 'T33',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 163,
    zeroToHundred: 9.6,
    drivetrain: 'AWD',
    priceRub: 3100000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'nissan_gtr',
    make: 'Nissan',
    model: 'GT-R',
    generation: 'R35',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 570,
    zeroToHundred: 2.9,
    drivetrain: 'AWD',
    priceRub: 14000000,
    rarity: Rarity.epic,
    aliases: ['gtr', 'godzilla'],
  ),
  CarSpec(
    id: 'nissan_silvia',
    make: 'Nissan',
    model: 'Silvia',
    generation: 'S15',
    yearFrom: 1999,
    yearTo: 2002,
    bodyType: 'купе',
    horsepower: 250,
    zeroToHundred: 5.5,
    drivetrain: 'RWD',
    priceRub: 4500000,
    rarity: Rarity.epic,
    aliases: ['s15', '200sx'],
  ),
  CarSpec(
    id: 'nissan_skyline',
    make: 'Nissan',
    model: 'Skyline GT-R',
    generation: 'R34',
    yearFrom: 1999,
    yearTo: 2002,
    bodyType: 'купе',
    horsepower: 280,
    zeroToHundred: 4.9,
    drivetrain: 'AWD',
    priceRub: 12000000,
    rarity: Rarity.legendary,
    aliases: ['r34', 'gtr r34'],
  ),
  CarSpec(
    id: 'nissan_370z',
    make: 'Nissan',
    model: '370Z',
    generation: 'Z34',
    yearFrom: 2009,
    yearTo: 2020,
    bodyType: 'купе',
    horsepower: 328,
    zeroToHundred: 5.3,
    drivetrain: 'RWD',
    priceRub: 3200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'subaru_wrx',
    make: 'Subaru',
    model: 'WRX',
    generation: 'VB',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 275,
    zeroToHundred: 5.4,
    drivetrain: 'AWD',
    priceRub: 5200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'subaru_forester',
    make: 'Subaru',
    model: 'Forester',
    generation: 'SK',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 150,
    zeroToHundred: 10.3,
    drivetrain: 'AWD',
    priceRub: 2900000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'subaru_impreza',
    make: 'Subaru',
    model: 'Impreza WRX STI',
    generation: 'GR',
    yearFrom: 2008,
    yearTo: 2014,
    bodyType: 'седан',
    horsepower: 300,
    zeroToHundred: 5.2,
    drivetrain: 'AWD',
    priceRub: 2800000,
    rarity: Rarity.epic,
    aliases: ['sti'],
  ),
  CarSpec(
    id: 'mitsubishi_outlander',
    make: 'Mitsubishi',
    model: 'Outlander',
    generation: 'IV',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 181,
    zeroToHundred: 9.5,
    drivetrain: 'AWD',
    priceRub: 3300000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'mitsubishi_lancer',
    make: 'Mitsubishi',
    model: 'Lancer Evolution',
    generation: 'X',
    yearFrom: 2007,
    yearTo: 2016,
    bodyType: 'седан',
    horsepower: 295,
    zeroToHundred: 5.4,
    drivetrain: 'AWD',
    priceRub: 3500000,
    rarity: Rarity.epic,
    aliases: ['evo', 'лансер'],
  ),
  CarSpec(
    id: 'mitsubishi_pajero',
    make: 'Mitsubishi',
    model: 'Pajero',
    generation: 'IV',
    yearFrom: 2006,
    yearTo: 2021,
    bodyType: 'внедорожник',
    horsepower: 250,
    zeroToHundred: 10.0,
    drivetrain: 'AWD',
    priceRub: 2800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_3',
    make: 'BMW',
    model: '3 Series',
    generation: 'G20',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 258,
    zeroToHundred: 5.8,
    drivetrain: 'RWD',
    priceRub: 5200000,
    rarity: Rarity.rare,
    aliases: ['bmw 3', 'bmw 320', 'bmw 330'],
  ),
  CarSpec(
    id: 'bmw_5',
    make: 'BMW',
    model: '5 Series',
    generation: 'G60',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 286,
    zeroToHundred: 5.8,
    drivetrain: 'AWD',
    priceRub: 7800000,
    rarity: Rarity.rare,
    aliases: ['bmw 5', 'bmw 530'],
  ),
  CarSpec(
    id: 'bmw_7',
    make: 'BMW',
    model: '7 Series',
    generation: 'G70',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 380,
    zeroToHundred: 5.4,
    drivetrain: 'AWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'bmw_x1',
    make: 'BMW',
    model: 'X1',
    generation: 'U11',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 204,
    zeroToHundred: 7.4,
    drivetrain: 'AWD',
    priceRub: 4800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_x3',
    make: 'BMW',
    model: 'X3',
    generation: 'G01',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 248,
    zeroToHundred: 6.3,
    drivetrain: 'AWD',
    priceRub: 5600000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_x5',
    make: 'BMW',
    model: 'X5',
    generation: 'G05',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 5.5,
    drivetrain: 'AWD',
    priceRub: 9800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_x6',
    make: 'BMW',
    model: 'X6',
    generation: 'G06',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 5.3,
    drivetrain: 'AWD',
    priceRub: 10500000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_x7',
    make: 'BMW',
    model: 'X7',
    generation: 'G07',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 381,
    zeroToHundred: 5.8,
    drivetrain: 'AWD',
    priceRub: 11800000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'bmw_m3',
    make: 'BMW',
    model: 'M3',
    generation: 'G80',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 510,
    zeroToHundred: 3.9,
    drivetrain: 'AWD',
    priceRub: 14500000,
    rarity: Rarity.epic,
    aliases: ['m3 competition'],
  ),
  CarSpec(
    id: 'bmw_m4',
    make: 'BMW',
    model: 'M4',
    generation: 'G82',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 510,
    zeroToHundred: 3.5,
    drivetrain: 'AWD',
    priceRub: 14800000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'bmw_m5',
    make: 'BMW',
    model: 'M5',
    generation: 'F90',
    yearFrom: 2018,
    yearTo: 2023,
    bodyType: 'седан',
    horsepower: 625,
    zeroToHundred: 3.3,
    drivetrain: 'AWD',
    priceRub: 12800000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'bmw_z4',
    make: 'BMW',
    model: 'Z4',
    generation: 'G29',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'родстер',
    horsepower: 340,
    zeroToHundred: 4.5,
    drivetrain: 'RWD',
    priceRub: 7200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bmw_i8',
    make: 'BMW',
    model: 'i8',
    generation: 'I12',
    yearFrom: 2014,
    yearTo: 2020,
    bodyType: 'купе',
    horsepower: 374,
    zeroToHundred: 4.4,
    drivetrain: 'AWD',
    priceRub: 8500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'mercedes_a',
    make: 'Mercedes-Benz',
    model: 'A-Class',
    generation: 'W177',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'хэтчбек',
    horsepower: 224,
    zeroToHundred: 6.2,
    drivetrain: 'FWD',
    priceRub: 3900000,
    rarity: Rarity.common,
    aliases: ['a-class', 'a200'],
  ),
  CarSpec(
    id: 'mercedes_c',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    generation: 'W206',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 258,
    zeroToHundred: 6.0,
    drivetrain: 'RWD',
    priceRub: 6100000,
    rarity: Rarity.rare,
    aliases: ['mercedes c', 'c-class', 'c200', 'c300'],
  ),
  CarSpec(
    id: 'mercedes_e',
    make: 'Mercedes-Benz',
    model: 'E-Class',
    generation: 'W214',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 258,
    zeroToHundred: 6.1,
    drivetrain: 'AWD',
    priceRub: 8900000,
    rarity: Rarity.rare,
    aliases: ['mercedes e', 'e-class'],
  ),
  CarSpec(
    id: 'mercedes_s',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    generation: 'W223',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 435,
    zeroToHundred: 4.9,
    drivetrain: 'AWD',
    priceRub: 14500000,
    rarity: Rarity.epic,
    aliases: ['s-class', 's500'],
  ),
  CarSpec(
    id: 'mercedes_gla',
    make: 'Mercedes-Benz',
    model: 'GLA',
    generation: 'H247',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 224,
    zeroToHundred: 6.7,
    drivetrain: 'AWD',
    priceRub: 4200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'mercedes_glc',
    make: 'Mercedes-Benz',
    model: 'GLC',
    generation: 'X254',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 258,
    zeroToHundred: 6.2,
    drivetrain: 'AWD',
    priceRub: 7200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'mercedes_gle',
    make: 'Mercedes-Benz',
    model: 'GLE',
    generation: 'V167',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 381,
    zeroToHundred: 5.3,
    drivetrain: 'AWD',
    priceRub: 9800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'g_class',
    make: 'Mercedes-Benz',
    model: 'G-Class',
    generation: 'W463',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 585,
    zeroToHundred: 4.5,
    drivetrain: 'AWD',
    priceRub: 22000000,
    rarity: Rarity.epic,
    aliases: ['гелик', 'g-wagen', 'g63', 'g 63'],
  ),
  CarSpec(
    id: 'amg_c63',
    make: 'Mercedes-AMG',
    model: 'C63',
    generation: 'W206',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 680,
    zeroToHundred: 3.4,
    drivetrain: 'AWD',
    priceRub: 16800000,
    rarity: Rarity.epic,
    aliases: ['c63', 'c 63'],
  ),
  CarSpec(
    id: 'amg_gt',
    make: 'Mercedes-AMG',
    model: 'GT',
    generation: 'C190',
    yearFrom: 2015,
    yearTo: 2021,
    bodyType: 'купе',
    horsepower: 585,
    zeroToHundred: 3.6,
    drivetrain: 'RWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'audi_a3',
    make: 'Audi',
    model: 'A3',
    generation: '8Y',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 190,
    zeroToHundred: 6.8,
    drivetrain: 'FWD',
    priceRub: 3600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'audi_a4',
    make: 'Audi',
    model: 'A4',
    generation: 'B9',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 249,
    zeroToHundred: 5.8,
    drivetrain: 'AWD',
    priceRub: 4800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_a6',
    make: 'Audi',
    model: 'A6',
    generation: 'C8',
    yearFrom: 2018,
    yearTo: 2025,
    bodyType: 'седан',
    horsepower: 340,
    zeroToHundred: 5.1,
    drivetrain: 'AWD',
    priceRub: 7200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_a8',
    make: 'Audi',
    model: 'A8',
    generation: 'D5',
    yearFrom: 2017,
    yearTo: 2025,
    bodyType: 'седан',
    horsepower: 460,
    zeroToHundred: 4.4,
    drivetrain: 'AWD',
    priceRub: 11200000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'audi_q5',
    make: 'Audi',
    model: 'Q5',
    generation: 'FY',
    yearFrom: 2017,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 249,
    zeroToHundred: 6.3,
    drivetrain: 'AWD',
    priceRub: 5400000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_q7',
    make: 'Audi',
    model: 'Q7',
    generation: '4M',
    yearFrom: 2015,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 5.7,
    drivetrain: 'AWD',
    priceRub: 7800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_q8',
    make: 'Audi',
    model: 'Q8',
    generation: '4M',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 5.6,
    drivetrain: 'AWD',
    priceRub: 9200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_tt',
    make: 'Audi',
    model: 'TT',
    generation: '8S',
    yearFrom: 2014,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 245,
    zeroToHundred: 5.2,
    drivetrain: 'AWD',
    priceRub: 3800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'audi_rs3',
    make: 'Audi',
    model: 'RS3',
    generation: '8Y',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 400,
    zeroToHundred: 3.8,
    drivetrain: 'AWD',
    priceRub: 8900000,
    rarity: Rarity.epic,
    aliases: ['rs3'],
  ),
  CarSpec(
    id: 'audi_rs6',
    make: 'Audi',
    model: 'RS6 Avant',
    generation: 'C8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'универсал',
    horsepower: 630,
    zeroToHundred: 3.4,
    drivetrain: 'AWD',
    priceRub: 17500000,
    rarity: Rarity.epic,
    aliases: ['rs6', 'rs 6'],
  ),
  CarSpec(
    id: 'audi_rs7',
    make: 'Audi',
    model: 'RS7',
    generation: 'C8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'лифтбек',
    horsepower: 630,
    zeroToHundred: 3.4,
    drivetrain: 'AWD',
    priceRub: 16800000,
    rarity: Rarity.epic,
    aliases: ['rs7'],
  ),
  CarSpec(
    id: 'audi_r8',
    make: 'Audi',
    model: 'R8',
    generation: '4S',
    yearFrom: 2019,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 620,
    zeroToHundred: 3.1,
    drivetrain: 'AWD',
    priceRub: 21000000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'porsche_macan',
    make: 'Porsche',
    model: 'Macan',
    generation: 'I',
    yearFrom: 2019,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 265,
    zeroToHundred: 6.2,
    drivetrain: 'AWD',
    priceRub: 7900000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'porsche_cayenne',
    make: 'Porsche',
    model: 'Cayenne',
    generation: 'III',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 340,
    zeroToHundred: 6.2,
    drivetrain: 'AWD',
    priceRub: 11200000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'porsche_panamera',
    make: 'Porsche',
    model: 'Panamera',
    generation: 'G2',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'лифтбек',
    horsepower: 330,
    zeroToHundred: 5.6,
    drivetrain: 'AWD',
    priceRub: 10800000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'porsche_911',
    make: 'Porsche',
    model: '911 Carrera',
    generation: '992',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 394,
    zeroToHundred: 4.0,
    drivetrain: 'RWD',
    priceRub: 18500000,
    rarity: Rarity.epic,
    aliases: ['911', 'carrera'],
  ),
  CarSpec(
    id: 'porsche_gt3rs',
    make: 'Porsche',
    model: '911 GT3 RS',
    generation: '992',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 525,
    zeroToHundred: 3.2,
    drivetrain: 'RWD',
    priceRub: 42000000,
    rarity: Rarity.legendary,
    aliases: ['gt3 rs', 'gt3rs'],
  ),
  CarSpec(
    id: 'porsche_taycan',
    make: 'Porsche',
    model: 'Taycan',
    generation: 'I',
    yearFrom: 2019,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 476,
    zeroToHundred: 4.0,
    drivetrain: 'AWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'porsche_718',
    make: 'Porsche',
    model: '718 Cayman',
    generation: '982',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 300,
    zeroToHundred: 4.9,
    drivetrain: 'RWD',
    priceRub: 8200000,
    rarity: Rarity.epic,
    aliases: ['cayman'],
  ),
  CarSpec(
    id: 'lexus_rx',
    make: 'Lexus',
    model: 'RX',
    generation: 'AL30',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 279,
    zeroToHundred: 7.0,
    drivetrain: 'AWD',
    priceRub: 8500000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'lexus_es',
    make: 'Lexus',
    model: 'ES',
    generation: 'XZ10',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 249,
    zeroToHundred: 8.3,
    drivetrain: 'FWD',
    priceRub: 5200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'lexus_lx',
    make: 'Lexus',
    model: 'LX',
    generation: 'J310',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 409,
    zeroToHundred: 7.2,
    drivetrain: 'AWD',
    priceRub: 16500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'lexus_is',
    make: 'Lexus',
    model: 'IS',
    generation: 'XE30',
    yearFrom: 2013,
    yearTo: 2024,
    bodyType: 'седан',
    horsepower: 241,
    zeroToHundred: 7.0,
    drivetrain: 'RWD',
    priceRub: 3800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'volvo_xc60',
    make: 'Volvo',
    model: 'XC60',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 250,
    zeroToHundred: 6.8,
    drivetrain: 'AWD',
    priceRub: 5200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'volvo_xc90',
    make: 'Volvo',
    model: 'XC90',
    generation: 'II',
    yearFrom: 2015,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 320,
    zeroToHundred: 6.5,
    drivetrain: 'AWD',
    priceRub: 6800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'landrover_def',
    make: 'Land Rover',
    model: 'Defender',
    generation: 'L663',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 300,
    zeroToHundred: 6.7,
    drivetrain: 'AWD',
    priceRub: 9800000,
    rarity: Rarity.epic,
    aliases: ['defender'],
  ),
  CarSpec(
    id: 'range_rover',
    make: 'Land Rover',
    model: 'Range Rover',
    generation: 'L460',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 400,
    zeroToHundred: 5.5,
    drivetrain: 'AWD',
    priceRub: 16500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'jaguar_ftype',
    make: 'Jaguar',
    model: 'F-Type',
    generation: 'X152',
    yearFrom: 2013,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 450,
    zeroToHundred: 4.4,
    drivetrain: 'RWD',
    priceRub: 7200000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'tesla_3',
    make: 'Tesla',
    model: 'Model 3',
    generation: 'Highland',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 366,
    zeroToHundred: 4.4,
    drivetrain: 'RWD',
    priceRub: 4800000,
    rarity: Rarity.rare,
    aliases: ['model 3'],
  ),
  CarSpec(
    id: 'tesla_y',
    make: 'Tesla',
    model: 'Model Y',
    generation: 'Juniper',
    yearFrom: 2025,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 379,
    zeroToHundred: 4.8,
    drivetrain: 'AWD',
    priceRub: 5600000,
    rarity: Rarity.rare,
    aliases: ['model y'],
  ),
  CarSpec(
    id: 'tesla_s',
    make: 'Tesla',
    model: 'Model S',
    generation: 'Plaid',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'лифтбек',
    horsepower: 1020,
    zeroToHundred: 2.1,
    drivetrain: 'AWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
    aliases: ['model s', 'plaid'],
  ),
  CarSpec(
    id: 'tesla_x',
    make: 'Tesla',
    model: 'Model X',
    generation: 'Plaid',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 1020,
    zeroToHundred: 2.6,
    drivetrain: 'AWD',
    priceRub: 13800000,
    rarity: Rarity.epic,
    aliases: ['model x'],
  ),
  CarSpec(
    id: 'tesla_cyber',
    make: 'Tesla',
    model: 'Cybertruck',
    generation: 'I',
    yearFrom: 2023,
    yearTo: 2026,
    bodyType: 'пикап',
    horsepower: 845,
    zeroToHundred: 2.9,
    drivetrain: 'AWD',
    priceRub: 14500000,
    rarity: Rarity.epic,
    aliases: ['cybertruck'],
  ),
  CarSpec(
    id: 'ford_focus',
    make: 'Ford',
    model: 'Focus',
    generation: 'IV',
    yearFrom: 2018,
    yearTo: 2024,
    bodyType: 'хэтчбек',
    horsepower: 150,
    zeroToHundred: 8.8,
    drivetrain: 'FWD',
    priceRub: 1800000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'ford_f150',
    make: 'Ford',
    model: 'F-150',
    generation: 'P702',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'пикап',
    horsepower: 400,
    zeroToHundred: 5.4,
    drivetrain: 'AWD',
    priceRub: 7200000,
    rarity: Rarity.rare,
    aliases: ['f150', 'f-150'],
  ),
  CarSpec(
    id: 'mustang_gt',
    make: 'Ford',
    model: 'Mustang GT',
    generation: 'S650',
    yearFrom: 2024,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 486,
    zeroToHundred: 4.3,
    drivetrain: 'RWD',
    priceRub: 8900000,
    rarity: Rarity.epic,
    aliases: ['mustang'],
  ),
  CarSpec(
    id: 'ford_gt',
    make: 'Ford',
    model: 'GT',
    generation: 'II',
    yearFrom: 2017,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 660,
    zeroToHundred: 3.0,
    drivetrain: 'RWD',
    priceRub: 45000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'chevrolet_camaro',
    make: 'Chevrolet',
    model: 'Camaro',
    generation: 'VI',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 455,
    zeroToHundred: 4.0,
    drivetrain: 'RWD',
    priceRub: 6200000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'corvette_c8',
    make: 'Chevrolet',
    model: 'Corvette',
    generation: 'C8',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 495,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    priceRub: 12500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'chevrolet_tahoe',
    make: 'Chevrolet',
    model: 'Tahoe',
    generation: 'V',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 420,
    zeroToHundred: 6.1,
    drivetrain: 'AWD',
    priceRub: 9800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'dodge_challenger',
    make: 'Dodge',
    model: 'Challenger Hellcat',
    generation: 'LC',
    yearFrom: 2015,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 717,
    zeroToHundred: 3.6,
    drivetrain: 'RWD',
    priceRub: 8900000,
    rarity: Rarity.epic,
    aliases: ['hellcat', 'challenger'],
  ),
  CarSpec(
    id: 'jeep_wrangler',
    make: 'Jeep',
    model: 'Wrangler',
    generation: 'JL',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 272,
    zeroToHundred: 7.5,
    drivetrain: 'AWD',
    priceRub: 6200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'jeep_gc',
    make: 'Jeep',
    model: 'Grand Cherokee',
    generation: 'WL',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 293,
    zeroToHundred: 7.5,
    drivetrain: 'AWD',
    priceRub: 6800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'cadillac_esc',
    make: 'Cadillac',
    model: 'Escalade',
    generation: 'V',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 420,
    zeroToHundred: 6.1,
    drivetrain: 'AWD',
    priceRub: 14500000,
    rarity: Rarity.epic,
  ),
  CarSpec(
    id: 'mini_cooper',
    make: 'Mini',
    model: 'Cooper S',
    generation: 'F56',
    yearFrom: 2014,
    yearTo: 2024,
    bodyType: 'хэтчбек',
    horsepower: 192,
    zeroToHundred: 6.8,
    drivetrain: 'FWD',
    priceRub: 2400000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'fiat_500',
    make: 'Fiat',
    model: '500',
    generation: 'III',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'хэтчбек',
    horsepower: 118,
    zeroToHundred: 9.0,
    drivetrain: 'FWD',
    priceRub: 2200000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'peugeot_3008',
    make: 'Peugeot',
    model: '3008',
    generation: 'II',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'кроссовер',
    horsepower: 180,
    zeroToHundred: 8.9,
    drivetrain: 'FWD',
    priceRub: 2600000,
    rarity: Rarity.common,
  ),
  CarSpec(
    id: 'suzuki_jimny',
    make: 'Suzuki',
    model: 'Jimny',
    generation: 'IV',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 102,
    zeroToHundred: 12.5,
    drivetrain: 'AWD',
    priceRub: 2800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'infiniti_qx80',
    make: 'Infiniti',
    model: 'QX80',
    generation: 'Z62',
    yearFrom: 2014,
    yearTo: 2024,
    bodyType: 'внедорожник',
    horsepower: 400,
    zeroToHundred: 6.5,
    drivetrain: 'AWD',
    priceRub: 7800000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'genesis_g70',
    make: 'Genesis',
    model: 'G70',
    generation: 'I',
    yearFrom: 2017,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 252,
    zeroToHundred: 5.9,
    drivetrain: 'RWD',
    priceRub: 4200000,
    rarity: Rarity.rare,
  ),
  CarSpec(
    id: 'bentley_conti',
    make: 'Bentley',
    model: 'Continental GT',
    generation: 'III',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 659,
    zeroToHundred: 3.6,
    drivetrain: 'AWD',
    priceRub: 28000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'rr_phantom',
    make: 'Rolls-Royce',
    model: 'Phantom',
    generation: 'VIII',
    yearFrom: 2017,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 571,
    zeroToHundred: 5.3,
    drivetrain: 'RWD',
    priceRub: 70000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'rr_cullinan',
    make: 'Rolls-Royce',
    model: 'Cullinan',
    generation: 'I',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'внедорожник',
    horsepower: 571,
    zeroToHundred: 5.2,
    drivetrain: 'AWD',
    priceRub: 52000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'aston_db11',
    make: 'Aston Martin',
    model: 'DB11',
    generation: 'I',
    yearFrom: 2016,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 630,
    zeroToHundred: 3.7,
    drivetrain: 'RWD',
    priceRub: 22000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'maserati_mc20',
    make: 'Maserati',
    model: 'MC20',
    generation: 'I',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 630,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    priceRub: 28000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'alfa_giulia',
    make: 'Alfa Romeo',
    model: 'Giulia Quadrifoglio',
    generation: 'I',
    yearFrom: 2016,
    yearTo: 2026,
    bodyType: 'седан',
    horsepower: 510,
    zeroToHundred: 3.9,
    drivetrain: 'RWD',
    priceRub: 8900000,
    rarity: Rarity.epic,
    aliases: ['giulia'],
  ),
  CarSpec(
    id: 'ferrari_f8',
    make: 'Ferrari',
    model: 'F8 Tributo',
    generation: 'F8',
    yearFrom: 2019,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 720,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    priceRub: 38000000,
    rarity: Rarity.legendary,
    aliases: ['f8'],
  ),
  CarSpec(
    id: 'ferrari_roma',
    make: 'Ferrari',
    model: 'Roma',
    generation: 'I',
    yearFrom: 2020,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 620,
    zeroToHundred: 3.4,
    drivetrain: 'RWD',
    priceRub: 28000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'ferrari_296',
    make: 'Ferrari',
    model: '296 GTB',
    generation: 'I',
    yearFrom: 2022,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 830,
    zeroToHundred: 2.9,
    drivetrain: 'RWD',
    priceRub: 42000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'ferrari_sf90',
    make: 'Ferrari',
    model: 'SF90 Stradale',
    generation: 'SF90',
    yearFrom: 2019,
    yearTo: 2025,
    bodyType: 'купе',
    horsepower: 1000,
    zeroToHundred: 2.5,
    drivetrain: 'AWD',
    priceRub: 62000000,
    rarity: Rarity.legendary,
    aliases: ['sf90'],
  ),
  CarSpec(
    id: 'lambo_huracan',
    make: 'Lamborghini',
    model: 'Huracán',
    generation: 'LP610',
    yearFrom: 2014,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 640,
    zeroToHundred: 2.9,
    drivetrain: 'AWD',
    priceRub: 36000000,
    rarity: Rarity.legendary,
    aliases: ['huracan', 'huracán'],
  ),
  CarSpec(
    id: 'lambo_aventador',
    make: 'Lamborghini',
    model: 'Aventador',
    generation: 'SVJ',
    yearFrom: 2018,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 770,
    zeroToHundred: 2.8,
    drivetrain: 'AWD',
    priceRub: 55000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'lambo_urus',
    make: 'Lamborghini',
    model: 'Urus',
    generation: 'I',
    yearFrom: 2018,
    yearTo: 2026,
    bodyType: 'кроссовер',
    horsepower: 666,
    zeroToHundred: 3.6,
    drivetrain: 'AWD',
    priceRub: 32000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'mclaren_720s',
    make: 'McLaren',
    model: '720S',
    generation: 'P14',
    yearFrom: 2017,
    yearTo: 2023,
    bodyType: 'купе',
    horsepower: 720,
    zeroToHundred: 2.8,
    drivetrain: 'RWD',
    priceRub: 40000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'mclaren_p1',
    make: 'McLaren',
    model: 'P1',
    generation: 'I',
    yearFrom: 2013,
    yearTo: 2015,
    bodyType: 'купе',
    horsepower: 916,
    zeroToHundred: 2.8,
    drivetrain: 'RWD',
    priceRub: 120000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'bugatti_chiron',
    make: 'Bugatti',
    model: 'Chiron',
    generation: 'I',
    yearFrom: 2016,
    yearTo: 2024,
    bodyType: 'купе',
    horsepower: 1500,
    zeroToHundred: 2.4,
    drivetrain: 'AWD',
    priceRub: 280000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'koenigsegg_jesko',
    make: 'Koenigsegg',
    model: 'Jesko',
    generation: 'I',
    yearFrom: 2021,
    yearTo: 2026,
    bodyType: 'купе',
    horsepower: 1600,
    zeroToHundred: 2.5,
    drivetrain: 'RWD',
    priceRub: 320000000,
    rarity: Rarity.legendary,
  ),
  CarSpec(
    id: 'pagani_huayra',
    make: 'Pagani',
    model: 'Huayra',
    generation: 'I',
    yearFrom: 2012,
    yearTo: 2022,
    bodyType: 'купе',
    horsepower: 730,
    zeroToHundred: 3.0,
    drivetrain: 'RWD',
    priceRub: 180000000,
    rarity: Rarity.legendary,
  ),
];
